export const clothCategories = [
  "All",
  "Dresses",
  "Denim",
  "Jeans",
  "Jumpsuits",
  "Tops",
  "Jackets and Coats",
  "Pants",
  "Shorts",
  "Skirts",
  "Lougerie & underwear",
  "Leather",
  "Sweaters & knits",
];

export const clothSizes = [
  "xxs",
  "xs",
  "s",
  "m",
  "l",
  "xl",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
];

export const colors = [
  { color: "#f3ecdb", label: "Beige" },
  { color: "#f07b4e", label: "Purple" },
  { color: "#000000", label: "Black" },
  { color: "#f07b4e", label: "Orange" },
  { color: "#465ba3", label: "Blue" },
  { color: "#41854d", label: "Green" },
  { color: "#f3b121", label: "Gold" },
  { color: "#f2a1b1", label: "Pink" },
  { color: "#665147", label: "Brown" },
  { color: "#cac1b8", label: "Taupe" },
  { color: "#d23c47", label: "Red" },
  { color: "#d23c47", label: "Red" },
];
